# Generated by Django 2.2.6 on 2020-12-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gud_app', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
